// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Permissions.API.DbContexts;

#nullable disable

namespace Permissions.API.Migrations
{
    [DbContext(typeof(PermissionContext))]
    [Migration("20230324202934_AddNewPermissionType")]
    partial class AddNewPermissionType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Permissions.API.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmployeeForename")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmployeeSurname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("PermissionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PermissionType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionType");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeForename = "John",
                            EmployeeSurname = "Doe",
                            PermissionDate = new DateTime(2023, 3, 24, 15, 29, 34, 234, DateTimeKind.Local).AddTicks(1402),
                            PermissionType = 1
                        },
                        new
                        {
                            Id = 2,
                            EmployeeForename = "Mark",
                            EmployeeSurname = "Smith",
                            PermissionDate = new DateTime(2023, 3, 24, 15, 28, 34, 234, DateTimeKind.Local).AddTicks(1418),
                            PermissionType = 2
                        },
                        new
                        {
                            Id = 3,
                            EmployeeForename = "Jane",
                            EmployeeSurname = "Doe",
                            PermissionDate = new DateTime(2023, 3, 24, 15, 25, 34, 234, DateTimeKind.Local).AddTicks(1501),
                            PermissionType = 3
                        },
                        new
                        {
                            Id = 4,
                            EmployeeForename = "Mary",
                            EmployeeSurname = "Coptom",
                            PermissionDate = new DateTime(2023, 3, 24, 15, 24, 34, 234, DateTimeKind.Local).AddTicks(1503),
                            PermissionType = 4
                        },
                        new
                        {
                            Id = 5,
                            EmployeeForename = "John",
                            EmployeeSurname = "Carpenter",
                            PermissionDate = new DateTime(2023, 3, 24, 15, 19, 34, 234, DateTimeKind.Local).AddTicks(1504),
                            PermissionType = 1
                        });
                });

            modelBuilder.Entity("Permissions.API.Entities.PermissionTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("PermissionTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "FullControl"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Read"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Write"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Delete"
                        },
                        new
                        {
                            Id = 5,
                            Description = "List"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Deny"
                        });
                });

            modelBuilder.Entity("Permissions.API.Entities.Permission", b =>
                {
                    b.HasOne("Permissions.API.Entities.PermissionTypes", "PermissionTypes")
                        .WithMany()
                        .HasForeignKey("PermissionType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PermissionTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
